import type { Metadata } from 'next'
import './globals.css'
import Navbar from '@/components/navbar/Navbar'
import React from "react";
import StyledComponentsRegistry from "@/lib/AntdRegistry";
import ToasterProvider from '@/app/providers/ToasterProvider';
import GalleryProvider from '@/app/providers/GalleryProvider';
import SignalRProvider from './providers/SignalRProvider';
import { getCurrentUser } from '@/actions/authActions';

export const metadata: Metadata = {
  title: 'Carsties',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const user = await getCurrentUser();
  return (
    <html lang="en">
        
        <body>
          <GalleryProvider>
            
            <Navbar />
            <main className='container mx-auto px-5 pt-10'>
              <SignalRProvider environment={process.env.NODE_ENV} user={user}>
                {children}

              </SignalRProvider>
            </main>
            <ToasterProvider />
           
          </GalleryProvider>
        </body>
    </html>
  )
}
